# Generated by Django 5.1.4 on 2026-05-26 15:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('cv_url', models.URLField(blank=True, max_length=500)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('technical', 'Technical'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_verdict', models.CharField(blank=True, max_length=50)),
                ('ai_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='jobs.job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='accounts.profile')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='candidates.candidate')),
            ],
            options={
                'db_table': 'candidate_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['owner', 'stage'], name='candidates_owner_i_bc3932_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['job'], name='candidates_job_id_877c55_idx'),
        ),
    ]
